# Generated by Django 5.2.6 on 2025-09-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(help_text='Separate ingredients by new line.')),
                ('instructions', models.TextField()),
                ('prep_time', models.IntegerField(help_text='Add in minutes.')),
                ('cook_time', models.IntegerField(help_text='Add in minutes.')),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
