// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB53OvVcU2JSuzFDaQyp2eEq27rpWB1aiM',
    appId: '1:173121738021:web:37f5437d4b17985770b6cc',
    messagingSenderId: '173121738021',
    projectId: 'sou-chef-d9efb',
    authDomain: 'sou-chef-d9efb.firebaseapp.com',
    storageBucket: 'sou-chef-d9efb.firebasestorage.app',
    measurementId: 'G-JV3FFQ7G8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm3pd43ko3iqQ2_Th6nnTO36ahJyyPcr8',
    appId: '1:173121738021:android:5f1921beb5c6764070b6cc',
    messagingSenderId: '173121738021',
    projectId: 'sou-chef-d9efb',
    storageBucket: 'sou-chef-d9efb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2aZH-6Td3FPmUCRklogEFgJH5mSqTwG4',
    appId: '1:173121738021:ios:5501ddfc5c9b483570b6cc',
    messagingSenderId: '173121738021',
    projectId: 'sou-chef-d9efb',
    storageBucket: 'sou-chef-d9efb.firebasestorage.app',
    iosBundleId: 'com.example.souChefFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2aZH-6Td3FPmUCRklogEFgJH5mSqTwG4',
    appId: '1:173121738021:ios:5501ddfc5c9b483570b6cc',
    messagingSenderId: '173121738021',
    projectId: 'sou-chef-d9efb',
    storageBucket: 'sou-chef-d9efb.firebasestorage.app',
    iosBundleId: 'com.example.souChefFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB53OvVcU2JSuzFDaQyp2eEq27rpWB1aiM',
    appId: '1:173121738021:web:523228274f10b44670b6cc',
    messagingSenderId: '173121738021',
    projectId: 'sou-chef-d9efb',
    authDomain: 'sou-chef-d9efb.firebaseapp.com',
    storageBucket: 'sou-chef-d9efb.firebasestorage.app',
    measurementId: 'G-2YT58R44VQ',
  );
}
